Update ui.py
Patch for ImportError. 

FreeBSD 14.0
Python 3.11.14

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt' is currently running

error